### ISSUE TITLE
Restart device when first time click item to play. 

### ISSUE THREAD

**Issue by phuongphally** [boyan01/flutter-music-player#7]
I do release apk and install on real device Samsung  2`Galaxy S8 ` and `Galaxy S9` running android 8.0 It is the same result. 

Launch home with list items working well but when I try to click play item then It restart my phone. 

Because of copyright this library?

**Comment by boyan01** [comment]
The root cause is https://github.com/boyan01/flutter-music-player/blob/26a2ace08fd92f0708b03235c9e613876b002a2d/android/src/main/kotlin/tech/soit/quiet/player/PlayList.kt#L110

samsung FaceWidgetPlaybackStateMonitor try to analysis MediaSession#extras，but it's classloader  can not find MediaMetadataCompat.class , so the systemUI got a crash. WTF

**Comment by phuongphally** [comment]
@boyan01  that is so sad .
